# Generated by Django 5.2.5 on 2025-11-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
